### ISSUE TITLE
new release of ripgrep isn't building automatically

### ISSUE THREAD

**Issue by joshsleeper** [carlwgeorge/ripgrep-rpm#2]
# problem
ripgrep 0.8.0 has been released, but isn't building automatically.
Possibly related to the release note below.

## relevant release note for 0.8.0
For **downstream packagers**, the directory hierarchy in ripgrep's archive releases has changed. The root directory now only contains the executable, README and license. There is now a new directory called `doc` which contains the man page (previously in the root), a user guide (new), a FAQ (new) and the CHANGELOG (previously not included in release). The `complete` directory remains the same.

## ripgrep releases
https://github.com/BurntSushi/ripgrep/releases

## carlwgeorge/ripgrep copr builds
https://copr.fedorainfracloud.org/coprs/carlwgeorge/ripgrep/builds/

**Comment by joshsleeper** [comment]
Perfect, thanks @carlwgeorge!

**Comment by carlwgeorge** [comment]
You're welcome of course.

FYI the builds are not automatic.  I'm not affiliated with ripgrep or involved in it's development, I'm just a guy that likes RPM packaging.  I have to review each release for changes like you noticed and make the appropriate changes to the spec file in this repo.

**Comment by carlwgeorge** [comment]
Build is in progress.  https://copr.fedorainfracloud.org/coprs/carlwgeorge/ripgrep/build/714726/

**Comment by joshsleeper** [comment]
Ahh, I see. For some reason I thought the builds were set up to watch for ripgrep releases and build automatically.

In that case, I'll just try to give you a heads up (or maybe a PR if I feel brave) when new releases drop.

**Comment by carlwgeorge** [comment]
I had configured [Fedora notifications](https://apps.fedoraproject.org/notifications/) to email me when it noticed a new release in [Anitya](https://release-monitoring.org/project/15461/), but for some reason it failed to send.  I'll tinker with the settings and hopefully it works next time.
