### ISSUE TITLE
ripgrep 11.0.1 released

### ISSUE THREAD

**Issue by joshsleeper** [carlwgeorge/ripgrep-rpm#5]
Just a heads up that `ripgrep` cut another release just shortly ago (not even on crates.io yet).
The versioning scheme was adjusted with this release, shifting what would've been `0.11.0` to be `11.0.0` instead.
https://github.com/BurntSushi/ripgrep/releases/tag/11.0.0

**Comment by carlwgeorge** [comment]
Great new, my [Anitya](https://release-monitoring.org/project/15461/) monitoring worked this time and emailed me about this last night!

> This release increases the minimum supported Rust version from 1.28.0 to
1.34.0.

This means I'll need to wait for [rust-1.34.0-1.el7](https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2019-e3789f6015) to be promoted to stable first.

**Comment by joshsleeper** [comment]
polite bump that rust 1.34 was promoted to stable about a month ago so bumping ripgrep to 11.0.1 should be possible now!

**Comment by carlwgeorge** [comment]
Thanks for the reminder, it's built now.

https://copr.fedorainfracloud.org/coprs/carlwgeorge/ripgrep/build/930337/
